version: "3.9"

services:

  # -------------------------
  # Infrastructure
  # -------------------------

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # -------------------------
  # Databases
  # -------------------------

  auth-db:
    image: postgres:15
    container_name: auth-db
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    ports:
      - "5001:5432"

  patient-db:
    image: postgres:15
    container_name: patient-db
    environment:
      POSTGRES_DB: patientdb
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    ports:
      - "5000:5432"

  # -------------------------
  # Microservices
  # -------------------------

  auth-service:
    build: ./auth-service
    depends_on:
      - auth-db
    ports:
      - "4005:4005"
    environment:
      JWT_SECRET: "ee55c4b2f400cb8415f8efa582e356bd9e2cce4cbd0baf7033a71c7dd82920b6"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://auth-db:5432/authdb"
      SPRING_DATASOURCE_USERNAME: "admin_user"
      SPRING_DATASOURCE_PASSWORD: "password"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_SQL_INIT_MODE: "always"

  billing-service:
    build: ./billing-service
    ports:
      - "9001:9001"

  patient-service:
    build: ./patient-service
    depends_on:
      - kafka
      - billing-service
      - patient-db
    ports:
      - "4000:4000"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://patient-db:5432/patientdb"
      SPRING_DATASOURCE_USERNAME: "admin_user"
      SPRING_DATASOURCE_PASSWORD: "password"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_SQL_INIT_MODE: "always"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      BILLING_SERVICE_ADDRESS: "billing-service"

  analytics-service:
    build: ./analytics-service
    depends_on:
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"

  api-gateway:
    build: ./api-gateway
    depends_on:
      - auth-service
      - patient-service
    ports:
      - "4004:4004"
    environment:
      AUTH_SERVICE_URL: "http://auth-service:4005"